services:
  gptforwarder:
    # image: gptforwarder
    build: .
    ports:
        - "5000:5000"
    volumes:
        - ./config:/app/config
        - ./logs:/app/logs
    environment:
        LOGGING_LEVEL: WARNING